XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXXX
        XXXX X
            XXXXXXXXXXXX XXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXX XXXXX
            XXXXXXXXXXXXXXXX XXXXXXX
            XXXXXXXXXXXX XXXXXXX
            XXXXXXX XXXXXX
        X

        XXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXX X X XXXX XXXXXXX XX XX XXXXX
            XXXXXXXXXXX XXXXXXX
        X

        XX X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        X X
            XXXXXX XXXXXXXX
            XXXXXXXXXXXXXX XXXXX
        X

        XXXXXXX X
            XXXXXXXX XXXXXXXXXXXXX
            XXXXXXXX XXXX XXXXX
            XXXXXXXXXXXXXXXXX XXXXXXXX
            XXXXXX XXXXXX
            XXXXXXXXXXXXXX XXXX
            XXXXXXXXXXXXXXXX XXXXX
            XXXXXXXXXXXX XXXXX
        X

        XXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXX XXXXXXXX
        X
    XXXXXXXX
XXXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXX XXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
XXXXXX

XXXXXXX
XXXXXXX
