BBBBBBB BBBBBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBXX
            XXXXXX XXXXXXXX
        XXXXXXXXXXXXX
    XXXXXXX

BBBBBBBB

