# Generated by Django 5.1.5 on 2025-04-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_author_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
