# Generated by Django 5.1.5 on 2025-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='books'),
        ),
    ]
