BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
    XXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    BB BBBBBBBBBBBBBBBBBBBB
        XX XXXXXXBBB BBBBBBBBBBBBBXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
    BBBBB

    XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXX
        XXXX
            XXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
        XXXXXXXX
        BBB BBBB BB BBBBB
            XXXXXXX
            XXXX
                XXX XXXXXXXXXXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXXXXXXX
                XXXX
                    XX XXXXXXBBB BBBBBBBBBBBBB  BBBBBBBXX
                        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX
                    BB BBBBBBBBBBBBBBBBBBBBBBB

                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB  BBBBBBBXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    BBBBB
                    BB BBBBBBBBBBBBBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBB  BBBBBBBXX
                            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX
                    BBBBB
                XXXXX
            XXXXX
        BBBBBB
    XXXXXXXX


    BBBBBBB BBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBB
BBBBBBBB
