BBBBBBB BBBBBBBBBBB

BBBBB BBBBB XXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX
        BB BBBBBBBBBB
            XXXX XXXXXX
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        BBBB
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                 XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
        BBBBB
        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBB
                XX XXXXXXXXXXXX
            BBBB
                XXXXXXXX XXXXXXXX XXX
            BBBBB XXXX XXXX
            XX XXXXXXBBB BBBBBBBBBBBBXX
                XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXX

        XXXXXX
    XXXXXX
BBBBBBBB