BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
    XXXXXXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        BBBBBBBBBB
        
        
        
        
        
        
        
        XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBXX
            XXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX
BBBBBBBB