# Generated by Django 5.1.5 on 2025-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('librarian', 'Librarian'), ('reader', 'Reader')], default='reader', max_length=100),
        ),
    ]
