# Generated by Django 5.1.5 on 2025-04-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fileupload_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table='upload_file',
        ),
    ]
