# Generated by Django 5.1.5 on 2025-04-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileupload',
            table=None,
        ),
    ]
