# Generated by Django 5.1.5 on 2025-04-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
