# Generated by Django 5.1.5 on 2025-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_uploadfile_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
