# Generated by Django 5.1.5 on 2025-05-02 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 14, 24, 49, 145372, tzinfo=datetime.timezone.utc)),
        ),
    ]
