# Generated by Django 5.1.5 on 2025-05-02 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_code_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 14, 25, 2, 864047, tzinfo=datetime.timezone.utc)),
        ),
    ]
