# Generated by Django 5.1.5 on 2025-05-02 14:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_code_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expired_date',
            field=models.DateTimeField(default=accounts.models.exp_time_now),
        ),
    ]
