# Generated by Django 5.1.5 on 2025-05-02 14:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_code_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.PositiveIntegerField(default=accounts.models.generate_code),
        ),
    ]
