# Generated by Django 5.1.5 on 2025-04-23 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('from_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_from', to=settings.AUTH_USER_MODEL)),
                ('to_acc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
