XXXX XXXXXXXXXXXXXXXXX

    XXX XXXXXXXXXXXXXXXXXXX

        
        BB BBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBB
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB


        
        BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                         XXXXXXXXXXXXXXXXXXXXXXXXXX
            BBBB
                XXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                XXXXX
            BBBBB


        BBBBBB
        

        BB BBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBB
            XXX XXXXXXXXXXXXXXXX XXXXXXXXXX
                XX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX
        BBBBB

    XXXXX
XXXXXX